### ISSUE TITLE
Append link text to title with pipe separator

### ISSUE THREAD

**Issue by terescode** [terescode/blastcaster-wp#2]
E.g.

Title: 5 Coolest Things On Earth This Week
Link Text: GE Reports

Title should end up being:

5 Coolest Things On Earth This Week | GE Reports

Ideally this should be optional behavior.

**Comment by terescode** [comment]
@MfgStories I have been thinking about this one.  I don't think this is a very common thing to do.  If you look at articles on other sites they don't display the "attribution" in the title/headline.  It is more common to put the attribution in a separate element (e.g. "Sourced from Reuters ... etc ").  Also in looking at some of the posts with this format it is not very visually appealing.  What do you think if we were to instead focus on adding some sort of attribution fields that could be displayed either as part of the post or as metadata on a custom post type?

**Comment by MfgStories** [comment]
I started doing this because CD had no other way to indicate the source
I really like you idea of "Sourced from: " to display first just before the article text
By taking it out of the title it will also make tweeting it out with buffer much easier since I'm always having to delete the source from the tweet. 
Much better

**Comment by MfgStories** [comment]
After discussing this with you and thinking about it more this enhancement is NOT needed and should be closed

**Comment by terescode** [comment]
Per @MfgStories closing this.
