### ISSUE TITLE
Cannot use an Uploaded Image if Blaster has recommended images

### ISSUE THREAD

**Issue by MfgStories** [terescode/blastcaster-wp#28]
I wanted to replace the recommended images with an alternate uploaded image.  Blaster did not post and continued to ask for an image.

URL to Blast
http://www.gereports.com/da-vinci-code-2-0-3d-printing-digital-technologies-altering-face-aircraft-engine-manufacturing-italy/

**Comment by MfgStories** [comment]
In this case Blaster had no recommended images,  I did not want to use any of the "ALL" images however Blaster would not let me upload the attached image
www.manufacturing.net/news/2017/02/spacex-makes-good-space-station-delivery

![screen shot 2017-02-23 at 11 55 28 am](https://cloud.githubusercontent.com/assets/25268340/23269567/038c047a-f9bf-11e6-9800-0b3b251b6b1e.png)

![nasa dragon](https://cloud.githubusercontent.com/assets/25268340/23269573/06ced464-f9bf-11e6-86a9-9bc5f96441df.png)

**Comment by terescode** [comment]
@MfgStories The reason for this is because the file exceeds the maximum size.  Currently we have the maximum file size hardcoded at 300K.  The file above is 328K.  As it exceeds the maximum, PHP does not show it in the $_FILES array so we can't get at it.

Two things.

1. When this happens and until the size is made configurable (as part of the settings ticket), try web optimizing the image using [Kraken](https://kraken.io/web-interface)
2. With this ticket we should at least make the error message more meaningful.  We can deal with the configurable size as part of the settings ticket. #14.

**Comment by terescode** [comment]
Resolved by PR #30 
Deployed to manufacturingstories.com
