### ISSUE TITLE
Blaster looses image if error is encountered

### ISSUE THREAD

**Issue by MfgStories** [terescode/blastcaster-wp#9]
I think I found the cause of my previous problem.  I was creating a new blast and forgot to enter the description text.  The blaster generated an error message asking for the text field to be added.  I added the text and hit BLAST.  I then got a message that I had not added an image even though I originally did before the text error.  For some reason the link to the image file gets lost when BLASTER encounters an entry error.  Once I added the image again everything worked fine.

**Comment by terescode** [comment]
This is a technical limitation of uploads.  <input file="..." elements are read only.  They cannot be set so they can't be made "sticky", which used here means "set back to the same thing that was previously submitted".  This does *not* happen when you have selected an image from recommended or all since these images are not actually uploaded.
